name: Bot Deploy/Init

on: 
  workflow_dispatch:
    inputs:
      amogi:
        description: 'idk too'
        required: false
  schedule:
    - cron: '10 1,5,9,13,17,21 * * *'

jobs:
  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup jdk 16
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '16'
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}

